### ISSUE TITLE
'diffCoverageReport.classesDirs' file collection is empty.

### ISSUE THREAD

**Issue by grsky360** [form-com/diff-coverage-gradle#43] opened 2022-04-14 03:56 UTC
After upgrading from 0.8.1 to 0.9.0/0.9.1, diffCoverage task keep throwing exception that `'diffCoverageReport.classesDirs' file collection is empty.`

My gradle version is 4.10.3.

Here is my configurations

```groovy
subprojects {
	jacocoTestReport {
		dependsOn test
		group = "Reporting"
		description = "Generate Jacoco coverage reports"

		executionData files("${buildDir}/jacoco/jacoco.exec")
		sourceDirectories = files("${projectDir}/src/main/java")

		def generatedFilter = [
			'**/generated/**'
		]
		classDirectories = files(
			fileTree(dir: "${buildDir}/classes/java/main", excludes: generatedFilter),
			fileTree(dir: "${buildDir}/classes/main", excludes: generatedFilter)
		)

		reports {
			xml.enabled = true
			html.enabled = true
			csv.enabled = true
			xml.destination file("${buildDir}/reports/jacoco.xml")
			csv.destination file("${buildDir}/reports/jacoco.csv")
			html.destination file("${buildDir}/reports/fullCoverage")
		}

		afterEvaluate {
			classDirectories = files(classDirectories.files.collect {
				fileTree(dir: it, exclude: generatedFilter)
			})
		}
	}

	diffCoverageReport {
		def diffFile = System.getProperty('jacoco.diff.file') ?: ''
		def diffRepo = System.getProperty('jacoco.diff.repo') ?: 'origin'
		def diffBranch = System.getProperty('jacoco.diff.branch') ?: 'master'
		diffSource {
			if (diffFile) {
				file = diffFile
			} else {
				git.compareWith "refs/remotes/${diffRepo}/${diffBranch}"
			}
		}

		jacocoExecFiles = files(jacocoTestReport.executionData)
		classesDirs = files(jacocoTestReport.classDirectories)
		srcDirs = files(jacocoTestReport.sourceDirectories)

		reports {
			html = true
			csv = true
			xml = true
			baseReportDir = "${buildDir}/reports"
		}
	}
}
```

**Comment by SurpSG** [comment] 2022-04-15 08:13
Hi @grsky360 

I belive you should update your configuration as shown below:
```groovy
jacocoExecFiles = files(subprojects.jacocoTestReport.executionData)
classesDirs = files(subprojects.jacocoTestReport.classDirectories)
srcDirs = files(subprojects.jacocoTestReport.sourceDirectories)
```

Furthermore, you can delete this rows from your configuration. Starting from v0.9.0 DiffCoverage able to autoconfigurate `jacocoExecFiles`, `classesDirs` and `srcDirs` from JaCoCo configuration. 

----

Anyway, I'll add more meaningful error message for this case.

**Comment by grsky360** [comment] 2022-04-15 08:37
I tried remove them, but the error still occurs. And it's working in 0.8.1 before

**Comment by SurpSG** [comment] 2022-04-15 13:51
Ok, I'll try to repropuce the issue on Gradle 4.10.3

**Comment by grsky360** [comment] 2022-04-15 16:07
Thanks! I'll also try to create a demo projevt to reproduce it

**Comment by grsky360** [comment] 2022-04-18 08:49
@SurpSG Here is the reproducable project.
The main code is same as the issue description
https://github.com/grsky360/diff-coverage-demo

**Comment by SurpSG** [comment] 2022-04-18 20:26
@grsky360 
I've opened a PR to your demo project that fixes issues with your configuration
https://github.com/grsky360/diff-coverage-demo/pull/1

Closing this issue because it's not a bug.
I'll create some basic examples with best practices.

**Closed by SurpSG** 2022-04-18 20:26 UTC

**Comment by grsky360** [comment] 2022-04-19 05:56
Seems still not working in my side using your fix...

**Comment by grsky360** [comment] 2022-04-19 06:43
I think I found the root cause...
It happens when build directory not exist (Like after gradle clean)

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/13222125/163941908-a01cac5c-9160-418f-ba19-4bbdbc47b7fe.png">

**Comment by SurpSG** [comment] 2022-04-19 14:51
@grsky360 
Yep, reproduced the same behavior. For some reason gradle doesn't trigger compile and test tasks before diffCoverage when I execute:
```
./gradlew test diffCoverage
```
It's require more deep investigation.

If you don't have some specific project structure then just remove `jacocoTestReport.classDirectories` configuration.
Also, I've found out that replacing `fileTree()` with simple `files()` fixes the issue.

**Comment by grsky360** [comment] 2022-04-19 16:29
`files` seems working, just missing the filter logic. But it's not a big deal.
Thanks for helping debug and test, I'll use files firstly!

**Comment by SurpSG** [comment] 2022-04-19 16:47
Ok. I'll investigate this behavior on latest Gradle version as well. Possibly, it's a bug.

**Comment by SurpSG** [comment] 2022-04-25 11:12
I approve that it's bug. However, it was fixed when I've fixed another issue #37 😄 
Fix version `0.10.0`(not released yet)

**Comment by grsky360** [comment] 2022-04-26 03:49
Oh, I got this, thanks for deep dive!
May I know when will it be released?

**Comment by SurpSG** [comment] 2022-04-26 07:10
I guess, till the end of May

**Comment by grsky360** [comment] 2022-04-27 05:57
Is there a 0.10.0.SNAPSHOT version?
If yes, I want to know if #34 has been included?

**Comment by mkc450** [comment] 2023-03-10 10:17
@SurpSG I got the same issue. 
 I use version 0.9.5 which doesn't seem to have the above fix which you mentioned. 
 May I know by when will it be released?

**Comment by SurpSG** [comment] 2023-03-14 21:05
@mkc450 I'm not maintainer of the project anymore. 
We should ping @pmelamed

**Comment by mkc450** [comment] 2023-04-22 14:48
@pmelamed Can we please have any update here.

**Comment by pmelamed** [comment] 2023-04-25 09:46
I plan to publish new release until the end of this week

**Comment by grsky360** [comment] 2023-09-05 05:08
@pmelamed Hi, may I know when will the new release be published

**Comment by SurpSG** [comment] 2023-09-06 07:22
@grsky360 try https://github.com/SurpSG/delta-coverage-plugin
